characters = [
    "Yagami Light",
    "L",
    "Ryuk",
    "Misa Amane",
    "Near",
    "Mello",
    "Teru Mikami",
    "Sachiko Yagami",
    "Sayu Yagami",
    "David Hoope",
    "George Sairas",
    "Koreyoshi Kitamura",
    "Kanichi Takimura",
    "Yamamoto",
    "Taro Kagami",
    "Minoro Tanaka",
    "Sanami",
    "Ryotaro Sakajo",
    "Shiori Akino",
]
